# Generated by Django 3.2.9 on 2021-11-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('mood', models.CharField(max_length=100)),
                ('highs', models.CharField(max_length=100)),
                ('lows', models.CharField(max_length=100)),
                ('notes', models.TextField(max_length=1000)),
            ],
        ),
    ]
