# Generated by Django 3.2.9 on 2021-11-25 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_dating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dating',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='day',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dating',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
