# Generated by Django 3.2.9 on 2021-11-25 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211125_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
